# docker-compose.yml (for Docker Compose V1 compatibility)
version: '2.4' # Using a version supported by Docker Compose V1 clients

# Service definitions are directly at the root in V1, under 'services' in V2+
services:
  youtube-transcript-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-transcript-api-service
    ports:
      - "8000:8000" # Host_port:Container_port
    restart: unless-stopped # This directive was also supported in later V1 versions
